In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
df = pd.DataFrame(iris.data)
df.columns = ["sl", "sw", 'pl', 'pw']

In [4]:
#Function to find label for a value
#if MIN_Value <=val < (m + Mean_Value) / 2 then it is assigned label a
#if (m + Mean_Value) <=val < Mean_Value then it is assigned label b
#if (Mean_Value) <=val < (Mean_Value + MAX_Value)/2 then it is assigned label c
#if (Mean_Value + MAX_Value)/2 <=val <= MAX_Value  then it is assigned label d

def label(val, *boundaries):
    if (val < boundaries[0]):
        return 'a'
    elif (val < boundaries[1]):
        return 'b'
    elif (val < boundaries[2]):
        return 'c'
    else:
        return 'd'

#Function to convert a continuous data into labelled data
#There are 4 lables  - a, b, c, d
def toLabel(df, old_feature_name):
    second = df[old_feature_name].mean()
    minimum = df[old_feature_name].min()
    first = (minimum + second)/2
    maximum = df[old_feature_name].max()
    third = (maximum + second)/2
    return df[old_feature_name].apply(label, args= (first, second, third))

In [5]:
#Convert all columns to labelled data
df['sl_labeled'] = toLabel(df, 'sl')
df['sw_labeled'] = toLabel(df, 'sw')
df['pl_labeled'] = toLabel(df, 'pl')
df['pw_labeled'] = toLabel(df, 'pw')
df

sl   sw   pl   pw sl_labeled sw_labeled pl_labeled pw_labeled
0    5.1  3.5  1.4  0.2          b          c          a          a
1    4.9  3.0  1.4  0.2          a          b          a          a
2    4.7  3.2  1.3  0.2          a          c          a          a
3    4.6  3.1  1.5  0.2          a          c          a          a
4    5.0  3.6  1.4  0.2          a          c          a          a
..   ...  ...  ...  ...        ...        ...        ...        ...
145  6.7  3.0  5.2  2.3          c          b          c          d
146  6.3  2.5  5.0  1.9          c          a          c          d
147  6.5  3.0  5.2  2.0          c          b          c          d
148  6.2  3.4  5.4  2.3          c          c          d          d
149  5.9  3.0  5.1  1.8          c          b          c          c

[150 rows x 8 columns]

In [6]:
df

sl   sw   pl   pw sl_labeled sw_labeled pl_labeled pw_labeled
0    5.1  3.5  1.4  0.2          b          c          a          a
1    4.9  3.0  1.4  0.2          a          b          a          a
2    4.7  3.2  1.3  0.2          a          c          a          a
3    4.6  3.1  1.5  0.2          a          c          a          a
4    5.0  3.6  1.4  0.2          a          c          a          a
..   ...  ...  ...  ...        ...        ...        ...        ...
145  6.7  3.0  5.2  2.3          c          b          c          d
146  6.3  2.5  5.0  1.9          c          a          c          d
147  6.5  3.0  5.2  2.0          c          b          c          d
148  6.2  3.4  5.4  2.3          c          c          d          d
149  5.9  3.0  5.1  1.8          c          b          c          c

[150 rows x 8 columns]

In [7]:
df.drop(['sl', 'sw', 'pl', 'pw'], axis = 1, inplace = True)

In [8]:
set(df['sl_labeled'])

{'a', 'b', 'c', 'd'}

In [9]:
df.head()

sl_labeled sw_labeled pl_labeled pw_labeled
0          b          c          a          a
1          a          b          a          a
2          a          c          a          a
3          a          c          a          a
4          a          c          a          a

In [10]:
X = df.values

In [11]:
X

array([['b', 'c', 'a', 'a'],
       ['a', 'b', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'b', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'b', 'a', 'a'],
       ['a', 'b', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'b', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['a', 'c', 'a', 'a'],
       ['b', 'c', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['b', 'd', 'a', 'a'],
       ['a', '

In [12]:
Y = iris.target

In [13]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
feature_names = iris.feature_names
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
d = {}
for i in range(len(feature_names)):
    d[feature_names[i]] = d.get(feature_names[i],0) + i
d

{'sepal length (cm)': 0,
 'sepal width (cm)': 1,
 'petal length (cm)': 2,
 'petal width (cm)': 3}

In [16]:
def entropy(X_train_column_data,Y_train,classe):
    m1 = Y_train[np.where(X_train_column_data==classe)]
    total = len(m1)
    entropy = 0
    values,counts = np.unique(m1,return_counts=True)
    p = counts/total
    log_p = np.log(p)
    p_log_p = -p*log_p
    return p_log_p.sum()

def gain(X_train,Y_train,f,d):
    d_classes = {}
    unique_classes_in_f = set(X_train[:,d[f]])

    values,counts = np.unique(X_train[:,d[f]],return_counts=True)
    for i in range(len(values)):
        d_classes[values[i]] = d_classes.get(values[i],0)+counts[i] 
    info_f = 0
    for classe in unique_classes_in_f:
        info_f += (d_classes[classe]/len(X_train)) * entropy(X_train[:,d[f]],Y_train,classe)
    values1,counts1 = np.unique(Y_train,return_counts=True)
    total = len(Y_train)
    p = counts1/total
    log_p = np.log(p)
    p_log_p = -p*log_p
    info_original = p_log_p.sum()
    information_gain = info_original - info_f
    return information_gain,info_original
        
def d_T(X_train,Y_train,features,d,level):
    
    if(len(set(Y_train))==1):
        print("Level",level)
        x=0
        y=0
        z=0
        if (Y_train[0]==0):
            x=len(Y_train)
        elif (Y_train[0]==1):
            y=len(Y_train)
        else:
            z=len(Y_train)
        print("Count of 0",x)
        print("Count of 1",y)
        print("Count of 2",z)
        print("Current Entropy  is =  0.0")
        print("Reached Leaf Node")
        return
    if len(features) == 0:
        print("Level",level)
        print("Features Ended")
        values12,counts12 = np.unique(Y_train,return_counts=True)
        d_counts = {0:0,1:0,2:0}
        for i in range(len(values12)):
            d_counts[values12[i]] = counts12[i]
        print("Count of 0",d_counts[0])
        print("Count of 1",d_counts[1])
        print("Count of 2",d_counts[2])
        
        return
    
    max_gain = -99999
    feature_split = 0
    entropy = 0
    print("Level",level)
    print("Count of 0",len(Y_train[np.where(Y_train==0)]))
    print("Count of 1",len(Y_train[np.where(Y_train==1)]))
    print("Count of 2",len(Y_train[np.where(Y_train==2)]))
    for f in features:
        info_gain ,entropy_level = gain(X_train,Y_train,f,d)
        if (max_gain<info_gain):
            max_gain = info_gain
            entropy = entropy_level
            feature_split = f
    
    print("Current Entropy",entropy)
    print("Splitting on feature {} with information gain {}".format(feature_split,max_gain))
    
    li = []
    for i in features:
        if i!=feature_split:
            li.append(i)
    li=np.array(li)
    unique_class_in_feature_split = set(X_train[:,d[feature_split]])
    for class1 in unique_class_in_feature_split:
        X_train_classe = X_train[np.where(X_train[:,d[feature_split]]==class1)]
        Y_train_classe = Y_train[np.where(X_train[:,d[feature_split]]==class1)]
        print("----------------------------------")
        X1 = d_T(X_train_classe,Y_train_classe,li,d,level+1)
        

In [17]:
d_T(X,Y,feature_names,d,0)

Level 0
Count of 0 50
Count of 1 50
Count of 2 50
Current Entropy 1.0986122886681096
Splitting on feature petal width (cm) with information gain 0.8752583089296135
----------------------------------
Level 1
Count of 0 0
Count of 1 0
Count of 2 34
Current Entropy  is =  0.0
Reached Leaf Node
----------------------------------
Level 1
Count of 0 0
Count of 1 40
Count of 2 16
Current Entropy 0.5982695885852573
Splitting on feature petal length (cm) with information gain 0.21536778951600982
----------------------------------
Level 2
Count of 0 0
Count of 1 0
Count of 2 8
Current Entropy  is =  0.0
Reached Leaf Node
----------------------------------
Level 2
Count of 0 0
Count of 1 39
Count of 2 8
Current Entropy 0.45622342016761397
Splitting on feature sepal length (cm) with information gain 0.10945355973980492
----------------------------------
Level 3
Count of 0 0
Count of 1 14
Count of 2 0
Current Entropy  is =  0.0
Reached Leaf Node
----------------------------------
Level 3
Count of 0

In [18]:
x=[0,0,1,1]
y=[0,1,0,1]
d={"first":x,"second":y}

In [19]:
df3 = pd.DataFrame(d)

In [20]:
df3["Result"]=[0,1,1,1] 

In [21]:
df3

first  second  Result
0      0       0       0
1      0       1       1
2      1       0       1
3      1       1       1

In [22]:
y1 = df3["Result"].values

In [23]:
y1

array([0, 1, 1, 1], dtype=int64)

In [24]:
df3.drop("Result",axis=1,inplace=True)

In [25]:
df3

first  second
0      0       0
1      0       1
2      1       0
3      1       1

In [26]:
x1=df3.values

In [27]:
x1

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]], dtype=int64)

In [28]:
features = ["x1","x2"]

In [29]:
d={"x1":0,"x2":1}

In [30]:
d_T(x1,y1,features,d,0)

Level 0
Count of 0 1
Count of 1 3
Count of 2 0
Current Entropy 0.5623351446188083
Splitting on feature x1 with information gain 0.21576155433883565
----------------------------------
Level 1
Count of 0 1
Count of 1 1
Count of 2 0
Current Entropy 0.6931471805599453
Splitting on feature x2 with information gain 0.6931471805599453
----------------------------------
Level 2
Count of 0 1
Count of 1 0
Count of 2 0
Current Entropy  is =  0.0
Reached Leaf Node
----------------------------------
Level 2
Count of 0 0
Count of 1 1
Count of 2 0
Current Entropy  is =  0.0
Reached Leaf Node
----------------------------------
Level 1
Count of 0 0
Count of 1 2
Count of 2 0
Current Entropy  is =  0.0
Reached Leaf Node
